name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.17.1
        id: go
      - uses: actions/checkout@v2

      - name: Go Tests
        run: go test -v -tags=integration